In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('indian_roads_dataset.csv')

In [3]:
drop_cols = [
    "accident_id",
    "city",
    "state",
    "latitude",
    "longitude",
    "date",
    "time",
    "vehicles_involved",
    "casualties",
    "accident_severity",
    "cause",
    "traffic_density"
]

df_ml = df.drop(columns=drop_cols)

In [4]:
df_ml["festival"] = df_ml["festival"].fillna("No Festival")

In [5]:
df_ml.isnull().sum()

hour              0
day_of_week       0
is_weekend        0
road_type         0
lanes             0
traffic_signal    0
weather           0
visibility        0
temperature       0
is_peak_hour      0
festival          0
risk_score        0
dtype: int64

In [6]:
X = df_ml.drop("risk_score", axis=1)

y = df_ml["risk_score"]

In [7]:
cat_cols = X.select_dtypes(include="object").columns.tolist()
num_cols = X.select_dtypes(exclude="object").columns.tolist()

print("Categorical Features:")
print(cat_cols)

print("\nNumerical Features:")
print(num_cols)

Categorical Features:
['day_of_week', 'road_type', 'weather', 'visibility', 'festival']

Numerical Features:
['hour', 'is_weekend', 'lanes', 'traffic_signal', 'temperature', 'is_peak_hour']

The input features are divided into categorical and numerical variables. Categorical features will be encoded before model training, while numerical features will be used directly. This separation enables appropriate preprocessing for different data types.

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [9]:
#creating the encoder
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            cat_cols
        )
    ],
    remainder="passthrough"
)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [11]:
X_train_encoded = preprocessor.fit_transform(X_train) 
X_test_encoded = preprocessor.transform(X_test)

In [12]:
print("Training Shape :", X_train_encoded.shape)
print("Testing Shape  :", X_test_encoded.shape)

Training Shape : (16000, 27)
Testing Shape  : (4000, 27)

In [13]:
feature_names = preprocessor.get_feature_names_out()

print(feature_names)

['cat__day_of_week_Friday' 'cat__day_of_week_Monday'
 'cat__day_of_week_Saturday' 'cat__day_of_week_Sunday'
 'cat__day_of_week_Thursday' 'cat__day_of_week_Tuesday'
 'cat__day_of_week_Wednesday' 'cat__road_type_highway'
 'cat__road_type_rural' 'cat__road_type_urban' 'cat__weather_clear'
 'cat__weather_fog' 'cat__weather_rain' 'cat__visibility_high'
 'cat__visibility_low' 'cat__visibility_medium' 'cat__festival_Diwali'
 'cat__festival_Eid' 'cat__festival_Holi' 'cat__festival_New Year'
 'cat__festival_No Festival' 'remainder__hour' 'remainder__is_weekend'
 'remainder__lanes' 'remainder__traffic_signal' 'remainder__temperature'
 'remainder__is_peak_hour']

Model 1 : Linear Regression
Linear Regression is used as the baseline regression model to predict the Route Safety Index. Its performance will be compared with more advanced machine learning models.

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

In [15]:
lr = LinearRegression()

lr.fit(X_train_encoded, y_train)

LinearRegression()

In [16]:
y_pred = lr.predict(X_test_encoded)

In [17]:
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("RMSE:", rmse)
print("R² Score:", r2)

MAE : 0.10236654817450531
RMSE: 0.11487813599567394
R² Score: 0.7158944962712424

In [18]:
results = pd.DataFrame({
    "Model": ["Linear Regression"],
    "MAE": [mae],
    "RMSE": [rmse],
    "R2 Score": [r2]
})

results

               Model       MAE      RMSE  R2 Score
0  Linear Regression  0.102367  0.114878  0.715894

- The Linear Regression model achieved an R² score of 0.716, indicating that it explains approximately 71.6% of the variance in the target variable.
- The MAE of 0.102 suggests that the average prediction error is approximately 0.10 units on the Route Safety Index scale. These results establish a strong baseline for comparing more advanced regression models.

Model 2 : Decision Tree Regressor
- To check if a non-linear model improves performance.

In [19]:
from sklearn.tree import DecisionTreeRegressor

In [20]:
dt = DecisionTreeRegressor(random_state=42)

dt.fit(X_train_encoded, y_train)

DecisionTreeRegressor(random_state=42)

In [21]:
y_pred_dt = dt.predict(X_test_encoded)

In [22]:
mae_dt = mean_absolute_error(y_test, y_pred_dt)
rmse_dt = np.sqrt(mean_squared_error(y_test, y_pred_dt))
r2_dt = r2_score(y_test, y_pred_dt)

print("MAE :", mae_dt)
print("RMSE:", rmse_dt)
print("R² :", r2_dt)

MAE : 0.11355
RMSE: 0.1657256769483836
R² : 0.4087318435330807

In [23]:
results.loc[len(results)] = [
    "Decision Tree",
    mae_dt,
    rmse_dt,
    r2_dt
]

results

               Model       MAE      RMSE  R2 Score
0  Linear Regression  0.102367  0.114878  0.715894
1      Decision Tree  0.113550  0.165726  0.408732

The Decision Tree Regressor exhibited lower predictive performance than Linear Regression. The reduction in R² score and increase in prediction error indicate overfitting, where the model captures noise from the training data rather than generalizable patterns.

Model 3 : Random Forest
- Random Forest solves the overfitting problem by averaging predictions from many trees.

In [24]:
from sklearn.ensemble import RandomForestRegressor

In [25]:
rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

In [26]:
rf.fit(X_train_encoded, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [27]:
y_pred_rf = rf.predict(X_test_encoded)

In [28]:
mae_rf = mean_absolute_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)

print("MAE :", mae_rf)
print("RMSE:", rmse_rf)
print("R² :", r2_rf)

MAE : 0.10207975029761927
RMSE: 0.12011214245290429
R² : 0.6894162610011241

In [29]:
results.loc[len(results)] = [
    "Random Forest",
    mae_rf,
    rmse_rf,
    r2_rf
]

results

               Model       MAE      RMSE  R2 Score
0  Linear Regression  0.102367  0.114878  0.715894
1      Decision Tree  0.113550  0.165726  0.408732
2      Random Forest  0.102080  0.120112  0.689416

Model 4 : Gradient Boosting Regressor

In [30]:
from sklearn.ensemble import GradientBoostingRegressor

In [31]:
gbr = GradientBoostingRegressor(
    random_state=42
)

gbr.fit(X_train_encoded, y_train)

GradientBoostingRegressor(random_state=42)

In [32]:
y_pred_gbr = gbr.predict(X_test_encoded)

In [33]:
mae_gbr = mean_absolute_error(y_test, y_pred_gbr)
rmse_gbr = np.sqrt(mean_squared_error(y_test, y_pred_gbr))
r2_gbr = r2_score(y_test, y_pred_gbr)

print("MAE :", mae_gbr)
print("RMSE:", rmse_gbr)
print("R² :", r2_gbr)

MAE : 0.10093006745890122
RMSE: 0.11418933875620513
R² : 0.7192912159932789

In [34]:
results.loc[len(results)] = [
    "Gradient Boosting",
    mae_gbr,
    rmse_gbr,
    r2_gbr
]

results

               Model       MAE      RMSE  R2 Score
0  Linear Regression  0.102367  0.114878  0.715894
1      Decision Tree  0.113550  0.165726  0.408732
2      Random Forest  0.102080  0.120112  0.689416
3  Gradient Boosting  0.100930  0.114189  0.719291

Gradient Boosting Regressor achieved the best performance among the evaluated models, with the lowest MAE and RMSE and the highest R² score. This suggests that boosting-based ensemble learning is better able to capture the relationships between the input features and the target variable compared to Linear Regression and Decision Tree-based approaches.

Model 5 : XGBoost

In [35]:
from xgboost import XGBRegressor

In [36]:
xgb = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=5,
    random_state=42
)

In [37]:
xgb.fit(X_train_encoded, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [38]:
y_pred_xgb = xgb.predict(X_test_encoded)

In [39]:
mae_xgb = mean_absolute_error(y_test, y_pred_xgb)
rmse_xgb = np.sqrt(mean_squared_error(y_test, y_pred_xgb))
r2_xgb = r2_score(y_test, y_pred_xgb)

print("MAE :", mae_xgb)
print("RMSE:", rmse_xgb)
print("R² :", r2_xgb)

MAE : 0.10080419470183552
RMSE: 0.11490411419948054
R² : 0.7157659881765996

In [40]:
results.loc[len(results)] = [
    "XGBoost",
    mae_xgb,
    rmse_xgb,
    r2_xgb
]

results

               Model       MAE      RMSE  R2 Score
0  Linear Regression  0.102367  0.114878  0.715894
1      Decision Tree  0.113550  0.165726  0.408732
2      Random Forest  0.102080  0.120112  0.689416
3  Gradient Boosting  0.100930  0.114189  0.719291
4            XGBoost  0.100804  0.114904  0.715766